name: IntelliJ Plugin

on:
  push:
    paths:
      - 'src/IntelliJ/**'
      - '.github/workflows/intellij.yml'
  pull_request:
    paths:
      - 'src/IntelliJ/**'
      - '.github/workflows/intellij.yml'

env:
  VERSION: 1.38.${{ github.run_number }}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
      - name: Cache Gradle
        uses: actions/cache@v5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Update Version
        working-directory: src/IntelliJ
        shell: pwsh
        run: |
          ((Get-Content -Path gradle.properties -Raw) `
            -Replace "pluginVersion=0.1.0", "pluginVersion=${{ env.VERSION }}") `
            | Set-Content -Path gradle.properties
      - name: Build IntelliJ Plugin
        working-directory: src/IntelliJ
        run: ./gradlew buildPlugin --no-daemon
      - name: Archive plugin artifact
        uses: actions/upload-artifact@v6
        with:
          name: intellij-plugin
          path: src/IntelliJ/build/distributions/*.zip
